/*----- PROTECTED REGION ID(MytestClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        MytestClass.cpp
//
// description : C++ source for the MytestClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the «name» once per process.
//
// project :     TestinsVasil.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <MytestClass.h>

/*----- PROTECTED REGION END -----*/

//-------------------------------------------------------------------
/**
 *	Create MytestClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Mytest_class(const char *name) {
		return Mytest_ns::MytestClass::init(name);
	}
}


namespace Mytest_ns
{


//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
MytestClass *MytestClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		MytestClass::MytestClass(string &s)
 * description : 	constructor for the MytestClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
MytestClass::MytestClass(string &s):DeviceClass(s)
{
	cout2 << "Entering MytestClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(Mytest::Class::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::constructor

	cout2 << "Leaving MytestClass constructor" << endl;
}


//--------------------------------------------------------
/**
 * method : 		MytestClass::~MytestClass()
 * description : 	destructor for the MytestClass
 */
//--------------------------------------------------------
MytestClass::~MytestClass()
{
	/*----- PROTECTED REGION ID(Mytest::Class::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		MytestClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
MytestClass *MytestClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new MytestClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		MytestClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
MytestClass *MytestClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}




//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		MyReadScalarCommandClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *MyReadScalarCommandClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "MyReadScalarCommandClass::execute(): arrived" << endl;

	
	return insert((static_cast<Mytest *>(device))->my_read_scalar_command());
}
//--------------------------------------------------------
/**
 * method : 		ReadLocalDataFromTangoServerClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadLocalDataFromTangoServerClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ReadLocalDataFromTangoServerClass::execute(): arrived" << endl;

	
	return insert((static_cast<Mytest *>(device))->read_local_data_from_tango_server());
}
//--------------------------------------------------------
/**
 * method : 		GeneratingRandomDataImageClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GeneratingRandomDataImageClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "GeneratingRandomDataImageClass::execute(): arrived" << endl;

	
	return insert((static_cast<Mytest *>(device))->generating_random_data_image());
}
//--------------------------------------------------------
/**
 * method : 		SetDataImageClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetDataImageClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetDataImageClass::execute(): arrived" << endl;

	
	return insert((static_cast<Mytest *>(device))->set_data_image());
}
//--------------------------------------------------------
/**
 * method : 		Load16BitImgClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *Load16BitImgClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "Load16BitImgClass::execute(): arrived" << endl;

	
	return insert((static_cast<Mytest *>(device))->load16_bit_img());
}




//===================================================================
//	Properties management
//===================================================================

//--------------------------------------------------------
/**
 * method : 		MytestClass::get_class_property
 * description : 	Get the class property for specified name.
 *
 * @param	name  The property name
 */
//--------------------------------------------------------
Tango::DbDatum MytestClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Mytest::MytestClass::get_default_device_property()()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum MytestClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Mytest::MytestClass::get_default_class_property()()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum MytestClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Mytest::MytestClass::get_class_property()
 *	Description : //	Add your own code to initialize
 */
//--------------------------------------------------------
void MytestClass::get_class_property()
{
}


//--------------------------------------------------------
/**
 *	Method      : Mytest::MytestClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *	              For each property, add to wizard property name and description.
 *	              If default value has been set, add it to wizard property and.
 *	              store it in a DbDatum.
 */
//--------------------------------------------------------
void MytestClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;
	
	//	Set Default Class Properties

	//	Set Default Device Properties
}


//--------------------------------------------------------
/**
 *	Method      : Mytest::MytestClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void MytestClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("TestinsVasil");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Just for fun");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename("Mytest");
	filename += "Class.cpp";
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}




//===================================================================
//	Factory methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		MytestClass::device_factory
 * description : 	Create the device object(s)
 *                  and store them in the device list
 *
 * @param	*devlist_ptr	The device name list
 */
//--------------------------------------------------------
void MytestClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	/*----- PROTECTED REGION ID(Mytest::Class::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Mytest(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Mytest *dev = static_cast<Mytest *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(Mytest::Class::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::device_factory_after

	
}


//--------------------------------------------------------
/**
 *	Method      : Mytest::MytestClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *	              and store them in the attribute list
 */
//--------------------------------------------------------
void MytestClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(Mytest::Class::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::attribute_factory_before


	//	Attribute : ScalarDouble
	ScalarDoubleAttrib	*scalardouble = new ScalarDoubleAttrib();
	Tango::UserDefaultAttrProp	scalardouble_prop;
	//	description	not set for	ScalarDouble
	//	label	not set for	ScalarDouble
	//	unit	not set for	ScalarDouble
	//	standard_unit	not set for	ScalarDouble
	//	display_unit	not set for	ScalarDouble
	//	format	not set for	ScalarDouble
	//	max_value	not set for	ScalarDouble
	//	min_value	not set for	ScalarDouble
	//	max_alarm	not set for	ScalarDouble
	//	min_alarm	not set for	ScalarDouble
	//	max_warning	not set for	ScalarDouble
	//	min_warning	not set for	ScalarDouble
	//	delta_t	not set for	ScalarDouble
	//	delta_val	not set for	ScalarDouble
	scalardouble->set_default_properties(scalardouble_prop);
	//	Not Polled
	scalardouble->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	ScalarDouble does not fire change event
	//	ScalarDouble does not fire archive event
	//	ScalarDouble does not fire data_ready event
	att_list.push_back(scalardouble);

	//	Attribute : ScalarStr
	ScalarStrAttrib	*scalarstr = new ScalarStrAttrib();
	Tango::UserDefaultAttrProp	scalarstr_prop;
	//	description	not set for	ScalarStr
	//	label	not set for	ScalarStr
	//	unit	not set for	ScalarStr
	//	standard_unit	not set for	ScalarStr
	//	display_unit	not set for	ScalarStr
	//	format	not set for	ScalarStr
	//	max_value	not set for	ScalarStr
	//	min_value	not set for	ScalarStr
	//	max_alarm	not set for	ScalarStr
	//	min_alarm	not set for	ScalarStr
	//	max_warning	not set for	ScalarStr
	//	min_warning	not set for	ScalarStr
	//	delta_t	not set for	ScalarStr
	//	delta_val	not set for	ScalarStr
	scalarstr->set_default_properties(scalarstr_prop);
	//	Not Polled
	scalarstr->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	ScalarStr does not fire change event
	//	ScalarStr does not fire archive event
	//	ScalarStr does not fire data_ready event
	att_list.push_back(scalarstr);

	//	Attribute : FlipHorizontal
	FlipHorizontalAttrib	*fliphorizontal = new FlipHorizontalAttrib();
	Tango::UserDefaultAttrProp	fliphorizontal_prop;
	//	description	not set for	FlipHorizontal
	//	label	not set for	FlipHorizontal
	//	unit	not set for	FlipHorizontal
	//	standard_unit	not set for	FlipHorizontal
	//	display_unit	not set for	FlipHorizontal
	//	format	not set for	FlipHorizontal
	//	max_value	not set for	FlipHorizontal
	//	min_value	not set for	FlipHorizontal
	//	max_alarm	not set for	FlipHorizontal
	//	min_alarm	not set for	FlipHorizontal
	//	max_warning	not set for	FlipHorizontal
	//	min_warning	not set for	FlipHorizontal
	//	delta_t	not set for	FlipHorizontal
	//	delta_val	not set for	FlipHorizontal
	fliphorizontal->set_default_properties(fliphorizontal_prop);
	//	Not Polled
	fliphorizontal->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	FlipHorizontal does not fire change event
	//	FlipHorizontal does not fire archive event
	//	FlipHorizontal does not fire data_ready event
	att_list.push_back(fliphorizontal);

	//	Attribute : FlipVertical
	FlipVerticalAttrib	*flipvertical = new FlipVerticalAttrib();
	Tango::UserDefaultAttrProp	flipvertical_prop;
	//	description	not set for	FlipVertical
	//	label	not set for	FlipVertical
	//	unit	not set for	FlipVertical
	//	standard_unit	not set for	FlipVertical
	//	display_unit	not set for	FlipVertical
	//	format	not set for	FlipVertical
	//	max_value	not set for	FlipVertical
	//	min_value	not set for	FlipVertical
	//	max_alarm	not set for	FlipVertical
	//	min_alarm	not set for	FlipVertical
	//	max_warning	not set for	FlipVertical
	//	min_warning	not set for	FlipVertical
	//	delta_t	not set for	FlipVertical
	//	delta_val	not set for	FlipVertical
	flipvertical->set_default_properties(flipvertical_prop);
	//	Not Polled
	flipvertical->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	FlipVertical does not fire change event
	//	FlipVertical does not fire archive event
	//	FlipVertical does not fire data_ready event
	att_list.push_back(flipvertical);

	//	Attribute : Rotate
	RotateAttrib	*rotate = new RotateAttrib();
	Tango::UserDefaultAttrProp	rotate_prop;
	//	description	not set for	Rotate
	//	label	not set for	Rotate
	//	unit	not set for	Rotate
	//	standard_unit	not set for	Rotate
	//	display_unit	not set for	Rotate
	//	format	not set for	Rotate
	//	max_value	not set for	Rotate
	//	min_value	not set for	Rotate
	//	max_alarm	not set for	Rotate
	//	min_alarm	not set for	Rotate
	//	max_warning	not set for	Rotate
	//	min_warning	not set for	Rotate
	//	delta_t	not set for	Rotate
	//	delta_val	not set for	Rotate
	rotate->set_default_properties(rotate_prop);
	//	Not Polled
	rotate->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Rotate does not fire change event
	//	Rotate does not fire archive event
	//	Rotate does not fire data_ready event
	att_list.push_back(rotate);

	//	Attribute : TestImage
	TestImageAttrib	*testimage = new TestImageAttrib();
	Tango::UserDefaultAttrProp	testimage_prop;
	//	description	not set for	TestImage
	//	label	not set for	TestImage
	//	unit	not set for	TestImage
	//	standard_unit	not set for	TestImage
	//	display_unit	not set for	TestImage
	//	format	not set for	TestImage
	//	max_value	not set for	TestImage
	//	min_value	not set for	TestImage
	//	max_alarm	not set for	TestImage
	//	min_alarm	not set for	TestImage
	//	max_warning	not set for	TestImage
	//	min_warning	not set for	TestImage
	//	delta_t	not set for	TestImage
	//	delta_val	not set for	TestImage
	testimage->set_default_properties(testimage_prop);
	//	Not Polled
	testimage->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	TestImage does not fire change event
	//	TestImage does not fire archive event
	//	TestImage does not fire data_ready event
	att_list.push_back(testimage);

	//	Attribute : UShortImg
	UShortImgAttrib	*ushortimg = new UShortImgAttrib();
	Tango::UserDefaultAttrProp	ushortimg_prop;
	//	description	not set for	UShortImg
	//	label	not set for	UShortImg
	//	unit	not set for	UShortImg
	//	standard_unit	not set for	UShortImg
	//	display_unit	not set for	UShortImg
	//	format	not set for	UShortImg
	//	max_value	not set for	UShortImg
	//	min_value	not set for	UShortImg
	//	max_alarm	not set for	UShortImg
	//	min_alarm	not set for	UShortImg
	//	max_warning	not set for	UShortImg
	//	min_warning	not set for	UShortImg
	//	delta_t	not set for	UShortImg
	//	delta_val	not set for	UShortImg
	ushortimg->set_default_properties(ushortimg_prop);
	//	Not Polled
	ushortimg->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	UShortImg does not fire change event
	//	UShortImg does not fire archive event
	//	UShortImg does not fire data_ready event
	att_list.push_back(ushortimg);

	//	Attribute : UShortImgColor
	UShortImgColorAttrib	*ushortimgcolor = new UShortImgColorAttrib();
	Tango::UserDefaultAttrProp	ushortimgcolor_prop;
	//	description	not set for	UShortImgColor
	//	label	not set for	UShortImgColor
	//	unit	not set for	UShortImgColor
	//	standard_unit	not set for	UShortImgColor
	//	display_unit	not set for	UShortImgColor
	//	format	not set for	UShortImgColor
	//	max_value	not set for	UShortImgColor
	//	min_value	not set for	UShortImgColor
	//	max_alarm	not set for	UShortImgColor
	//	min_alarm	not set for	UShortImgColor
	//	max_warning	not set for	UShortImgColor
	//	min_warning	not set for	UShortImgColor
	//	delta_t	not set for	UShortImgColor
	//	delta_val	not set for	UShortImgColor
	ushortimgcolor->set_default_properties(ushortimgcolor_prop);
	//	Not Polled
	ushortimgcolor->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	UShortImgColor does not fire change event
	//	UShortImgColor does not fire archive event
	//	UShortImgColor does not fire data_ready event
	att_list.push_back(ushortimgcolor);

	//	Attribute : TestImageColor
	TestImageColorAttrib	*testimagecolor = new TestImageColorAttrib();
	Tango::UserDefaultAttrProp	testimagecolor_prop;
	//	description	not set for	TestImageColor
	//	label	not set for	TestImageColor
	//	unit	not set for	TestImageColor
	//	standard_unit	not set for	TestImageColor
	//	display_unit	not set for	TestImageColor
	//	format	not set for	TestImageColor
	//	max_value	not set for	TestImageColor
	//	min_value	not set for	TestImageColor
	//	max_alarm	not set for	TestImageColor
	//	min_alarm	not set for	TestImageColor
	//	max_warning	not set for	TestImageColor
	//	min_warning	not set for	TestImageColor
	//	delta_t	not set for	TestImageColor
	//	delta_val	not set for	TestImageColor
	testimagecolor->set_default_properties(testimagecolor_prop);
	//	Not Polled
	testimagecolor->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	TestImageColor does not fire change event
	//	TestImageColor does not fire archive event
	//	TestImageColor does not fire data_ready event
	att_list.push_back(testimagecolor);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());

	/*----- PROTECTED REGION ID(Mytest::Class::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::attribute_factory_after

}


//--------------------------------------------------------
/**
 *	Method      : Mytest::MytestClass::command_factory()
 *	Description : Create the command object(s)
 *	              and store them in the command list
 */
//--------------------------------------------------------
void MytestClass::command_factory()
{
	/*----- PROTECTED REGION ID(Mytest::Class::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::command_factory_before

	MyReadScalarCommandClass	*pMyReadScalarCommandCmd =
		new MyReadScalarCommandClass("MyReadScalarCommand",
			Tango::DEV_VOID, Tango::DEV_STRING,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pMyReadScalarCommandCmd);
	ReadLocalDataFromTangoServerClass	*pReadLocalDataFromTangoServerCmd =
		new ReadLocalDataFromTangoServerClass("ReadLocalDataFromTangoServer",
			Tango::DEV_VOID, Tango::DEV_STRING,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pReadLocalDataFromTangoServerCmd);
	GeneratingRandomDataImageClass	*pGeneratingRandomDataImageCmd =
		new GeneratingRandomDataImageClass("GeneratingRandomDataImage",
			Tango::DEV_VOID, Tango::DEV_LONG,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pGeneratingRandomDataImageCmd);
	SetDataImageClass	*pSetDataImageCmd =
		new SetDataImageClass("SetDataImage",
			Tango::DEV_VOID, Tango::DEV_ULONG,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetDataImageCmd);
	Load16BitImgClass	*pLoad16BitImgCmd =
		new Load16BitImgClass("Load16BitImg",
			Tango::DEV_VOID, Tango::DEV_BOOLEAN,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pLoad16BitImgCmd);

	/*----- PROTECTED REGION ID(Mytest::Class::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::command_factory_after

}




//===================================================================
//	Dynamic attributes related methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		MytestClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void MytestClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;


	/*----- PROTECTED REGION ID(Mytest::Class::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::create_static_att_list

}


//--------------------------------------------------------
/**
 * method : 		MytestClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void MytestClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Mytest *dev = static_cast<Mytest *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()],true);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(Mytest::Class::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::erase_dynamic_attributes

}



	/*----- PROTECTED REGION ID(Mytest::Class::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Mytest::Class::Additional Methods

} //	namespace
